- name: DHCP ip-topup
  hosts:  test
  gather_facts: no
  tasks:
    - name: get server date for receiving file
      shell:  date +'%Y%m%d'
      register: date
      delegate_to:  localhost
      run_once: true

    - name: debug date
      debug:
        msg: '{{ date.stdout }}'

    - name: get server date for log files
      shell:  date +'%Y-%m-%d-%H'
      register: log_date
      delegate_to:  localhost
      run_once: true

    - name: get server date for dhcp backup
      shell:  date +'%Y-%m-%d'
      register: dhcp_date
      delegate_to:  localhost
      run_once: true

    - name: debug dhcp date
      debug:
        msg: '{{ dhcp_date.stdout }}'

    - name: Print hosts list
      debug:
        #msg: "{{ group_names }}"
        msg: "{{ inventory_hostname }}"

    - name: Copy using inline content
      copy:
        content: '# This file was moved to /etc/other.conf'
        dest: /tmp/mine.conf
        owner: ansible_rw
        group: ansible_rw
        mode: '775'
